---
title: "r_best_practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I've been asked more and more about 


### 01. Use R projects. Always.

Human Civilization was built on conventions. R scripts have them, too. For example 
> Any resident R script is written assuming that it will be run from a fresh R process with working directory set to the project directory. It creates everything it needs, in its own workspace or folder, and it touches nothing it did not create.

You want your project to work. Not only now, but also in 5 years, even if folder and file paths change. Also, you want it to work when your collaborator runs it from their computer. Projects create convention that make it possible.

Basically, they create the nevironment where

1) all code and outputs are stored in one set location (no more `setwd()`!)
2) relative file paths are created - this guarantees better reproducibility 
3) clean R environment is created every time you open it (no more `rm(list = ls())`!) 

If you're not convinced, read [a more thourough explanation given by Jenny Bryan](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/). 

So, go on and start a New Project today!





### first thing: load necessary packages but also consider calling functions in a package via `::`

### describe he purpose of he code / project

### Name your code chunks and use them for navigation. 

### Make your life easier by using a red dot when you need to. 

### Write your code as if someone was going to use it without communicating with you. From day one
- commenting
- as clear and efficient as possible
- ideally timed and tested 


### name your files like a Pro.
- [Jenny Bryan's slides](https://t.co/99waX8liuQ)

### if you have to copy/paste bit of code at least 3 times, write a function. 


### With big, complex data projects, use project pipeline.

### Never save the working directory


### Before publshing/sharing your code, run it in the fresh workspace. 

